import { City, Place } from './types';

export const CITIES_DATA: City[] = [
  {
    id: 'paris',
    name: 'Paris',
    country: 'France',
    region: 'Europe',
    tagline: 'The timeless cadence of limestone facades, riverside bouquinistes, and salon dialogue.',
    editorialDescription:
      'Paris reveals herself not in grand monuments, but in the quiet transitions: the slant of zinc-roofed morning light through café curtains, the scent of beeswax and bookbinding along the Rue Bonaparte, and the contemplative hush of stone courtyards hidden behind sculpted carriage gates.',
    badge: 'Architecture & Haute Cuisine',
    heroImage: '/images/hero_paris.jpg',
    galleryImages: [
      '/images/hero_paris.jpg',
      '/images/place_paris_cafe.jpg',
      '/images/place_rome_pantheon.jpg',
    ],
    timezone: 'Europe/Paris',
    coordinates: { lat: 48.8566, lng: 2.3522 },
    weather: {
      tempC: 21,
      tempF: 70,
      condition: 'Clear & Golden Haze',
      humidity: '48%',
      wind: '9 km/h NW',
      goldenHour: '19:42',
      uvIndex: '3 (Moderate)',
      highLow: '23° / 14°',
    },
    insiderTips: [
      {
        id: 'tip-p1',
        title: 'The Courtyard Portals of Le Marais',
        category: 'Architecture Walk',
        description: 'Push past the heavy carriage doors along Rue des Francs-Bourgeois that appear ajar. Behind Hôtel de Sully lies an intact 17th-century private parterre garden connected directly to Place des Vosges, offering absolute silence.',
        curatorName: 'Clémence Delacroix',
        curatorRole: 'Architectural Historian & Contributor',
      },
      {
        id: 'tip-p2',
        title: 'Bistro Reservations Cadence',
        category: 'Dining Etiquette',
        description: 'For Michelin-vetted neo-bistros, tables open exactly 21 days in advance at midnight Central European Time. Never order bread alone; tear and dip into emulsified sauces rather than slicing with butter knives.',
        curatorName: 'Antoine de Saint-Germain',
        curatorRole: 'Gastronomy Editor',
      },
      {
        id: 'tip-p3',
        title: 'Morning Along the Quai de Conti',
        category: 'Solitary Solitude',
        description: 'Visit the riverbank between Pont des Arts and Pont Neuf at 07:15. The mist lifts off the Seine, reflecting the Institut de France dome before traffic starts.',
        curatorName: 'Éléonore Vance',
        curatorRole: 'ROMELY Paris Correspondent',
      },
    ],
    places: [
      {
        id: 'paris-cafe-de-flore',
        cityId: 'paris',
        name: 'Café de Flore',
        nativeName: 'Café de Flore',
        category: 'Cafes',
        tagline: 'The literary heart of Saint-Germain where existentialism and morning espresso meet.',
        description:
          'Founded in 1887 during the French Third Republic, Café de Flore remains the undisputed cathedral of Parisian intellectual cafe culture. Its Art Deco red banquettes, mirrored mahogany wainscoting, and polished brass coat stands have hosted Jean-Paul Sartre, Simone de Beauvoir, Pablo Picasso, and James Baldwin. Today, it still commands the street corner with flawless white-aproned garçons de café serving velvety chocolat chaud, single-origin espressos, and warm pain au chocolat on monogrammed porcelain.',
        editorialVerdict:
          'An irreplaceable rite of passage. Resist the urge to rush: arrive before 09:30 or after 22:00 for the most authentic literary serenity.',
        atmosphere: ['Historic Art Deco', 'Literary Heritage', 'Outdoor Terrace', 'People Watching'],
        rating: 9.7,
        curatorScore: '9.7 / 10 Curated',
        priceLevel: '€€€',
        neighborhood: 'Saint-Germain-des-Prés, 6th Arr.',
        address: '172 Boulevard Saint-Germain, 75006 Paris, France',
        phone: '+33 1 45 48 55 26',
        website: 'https://cafedeflore.fr',
        hours: [
          { days: 'Monday – Sunday', time: '07:30 – 01:30' },
          { days: 'Kitchen Service', time: 'Continuous all day' },
        ],
        bestTimeToVisit: 'Early morning (08:00 - 09:30) for quiet terrace reading; late evening (after 22:30) for digestifs.',
        dressCode: 'Smart Casual (refined Parisian tailoring preferred; athletic gymwear discouraged).',
        images: [
          '/images/place_paris_cafe.jpg',
          '/images/hero_paris.jpg',
          '/images/place_tokyo_garden.jpg',
        ],
        coordinates: { lat: 48.8542, lng: 2.3328 },
        insiderTip:
          'Ascend the narrow stairs to the first floor (premier étage). It is quieter than the ground floor terrace and offers elevated views through the arched lace-curtained windows.',
        curatorQuote: {
          text: 'There is no finer sensation in autumn than holding a hot porcelain cup here while watching the Boulevard awaken under golden plane trees.',
          curator: 'Hélène Roche',
          role: 'Senior Paris Editor',
        },
      },
      {
        id: 'paris-orangerie',
        cityId: 'paris',
        name: 'Musée de l\'Orangerie',
        nativeName: 'Musée de l’Orangerie',
        category: 'Museums',
        tagline: 'Monet’s monumental Water Lilies housed in an elliptical temple of natural light.',
        description:
          'Nestled at the western edge of the Tuileries Garden, the Orangerie offers an intimate, transcendent encounter with Claude Monet’s Nymphéas cycle. Commissioned in the wake of the 1918 armistice as an offering of peace, the eight monumental murals curve around two custom elliptical subterranean halls flooded with diffused skylight. Downstairs, the Walter-Guillaume collection features masterworks by Cézanne, Matisse, Modigliani, and Soutine in serene, human-scaled galleries.',
        editorialVerdict:
          'Unlike the cavernous Louvre, the Orangerie can be fully absorbed in 90 minutes of meditative quietude. Book the earliest timeslot.',
        atmosphere: ['Meditative Silence', 'Natural Zenithal Light', 'Impressionist Masterworks', 'Architectural Grace'],
        rating: 9.9,
        curatorScore: '9.9 / 10 Curated',
        priceLevel: '€€',
        neighborhood: 'Tuileries / 1st Arr.',
        address: 'Jardin des Tuileries, Place de la Concorde, 75001 Paris, France',
        phone: '+33 1 44 50 43 00',
        website: 'https://www.musee-orangerie.fr',
        hours: [
          { days: 'Wednesday – Monday', time: '09:00 – 18:00' },
          { days: 'Tuesday', time: 'Closed' },
        ],
        bestTimeToVisit: 'Wednesday morning at 09:00, when morning sunlight pours directly through the oval skylights.',
        dressCode: 'Elevated Casual.',
        images: [
          '/images/hero_paris.jpg',
          '/images/place_paris_cafe.jpg',
          '/images/place_rome_pantheon.jpg',
        ],
        coordinates: { lat: 48.8638, lng: 2.3226 },
        insiderTip:
          'Sit on the center oval bench in Room 1 for at least ten minutes without looking at a screen. Let your peripheral vision assimilate Monet’s undulating willow reflections.',
        curatorQuote: {
          text: 'It is the closest architecture has ever come to framing eternity.',
          curator: 'Marc-Aurèle Thierry',
          role: 'Curator of Fine Arts',
        },
      },
      {
        id: 'paris-place-des-vosges',
        cityId: 'paris',
        name: 'Place des Vosges & Arcades',
        nativeName: 'Place des Vosges',
        category: 'Landmarks',
        tagline: 'Paris’s oldest planned square, framed by symmetrical red brick and limestone arcades.',
        description:
          'Inaugurated in 1612 for the engagement of Louis XIII and Anne of Austria, Place des Vosges represents the pinnacle of early French classicism. Thirty-six identical pavilions featuring steeply pitched slate mansard roofs and vaulted stone arcades envelop a tranquil square planted with trimmed linden trees and murmuring neoclassical fountains. Under the vaulted arcades, contemporary art galleries, quiet antique dealers, and tea rooms provide serene refuge.',
        editorialVerdict:
          'The ultimate afternoon sanctuary for writers and contemplative walkers. The acoustics under the vaulted stone arcades are magical.',
        atmosphere: ['Renaissance Geometry', 'Linden Shade', 'Antique Galleries', 'Historic Splendor'],
        rating: 9.8,
        curatorScore: '9.8 / 10 Curated',
        priceLevel: '€',
        neighborhood: 'Le Marais, 4th Arr.',
        address: 'Place des Vosges, 75004 Paris, France',
        phone: '+33 1 42 76 40 40',
        website: 'https://www.paris.fr',
        hours: [
          { days: 'Public Square', time: 'Open daily from sunrise to sunset' },
          { days: 'Arcade Galleries', time: '11:00 – 19:00' },
        ],
        bestTimeToVisit: 'Late afternoon when the warm terracotta brickwork glows amber in the setting sun.',
        dressCode: 'Relaxed Elegant.',
        images: [
          '/images/hero_paris.jpg',
          '/images/place_paris_cafe.jpg',
        ],
        coordinates: { lat: 48.8556, lng: 2.3656 },
        insiderTip:
          'Take the discreet vaulted passageway at Pavilion 7 to enter the private gardens of Hôtel de Sully. A tranquil shortcut to Rue Saint-Antoine.',
        curatorQuote: {
          text: 'The geometric rhythm of the arches has an almost musical calming power on the hurried mind.',
          curator: 'Sylvie Laurent',
          role: 'Urban Heritage Specialist',
        },
      },
      {
        id: 'paris-le-gabriel',
        cityId: 'paris',
        name: 'Le Gabriel at La Réserve',
        nativeName: 'Le Gabriel — Jérôme Banctel',
        category: 'Restaurants',
        tagline: 'Three-Michelin-starred culinary poetry hidden in a discreet Haussmannian mansion.',
        description:
          'Set inside a private 19th-century hôtel particulier steps from the Élysée Palace, Le Gabriel is an oasis of quiet Parisian luxury. Chef Jérôme Banctel crafts transcendent tasting menus that juxtapose French classical technique with profound Japanese fermentation mastery. With only ten tables surrounded by embossed Cordoba leather walls, Napoleon III gilded paneling, and delicate Baccarat crystal, the service is whisper-quiet and peerless.',
        editorialVerdict:
          'One of the purest gastronomic expressions in Europe today. The pigeon prepared with Brittany seaweed and buckwheat is unforgettable.',
        atmosphere: ['3-Star Michelin', 'Private Mansion', 'Whisper-Quiet Service', 'Haute Gastronomy'],
        rating: 9.9,
        curatorScore: '9.9 / 10 Curated',
        priceLevel: '€€€€',
        neighborhood: 'Champs-Élysées, 8th Arr.',
        address: '42 Avenue Gabriel, 75008 Paris, France',
        phone: '+33 1 58 36 60 50',
        website: 'https://www.lareserve-paris.com',
        hours: [
          { days: 'Tuesday – Saturday', time: '12:30 – 14:00, 19:30 – 21:30' },
          { days: 'Sunday & Monday', time: 'Closed' },
        ],
        bestTimeToVisit: 'Dinner at 20:00 for the full 8-sequence sensory tasting journey.',
        dressCode: 'Formal Elegance (Jacket required for gentlemen; no sportswear).',
        images: [
          '/images/place_paris_cafe.jpg',
          '/images/hero_paris.jpg',
        ],
        coordinates: { lat: 48.8698, lng: 2.3134 },
        insiderTip:
          'Request Table 4 in the corner rotunda for maximum discretion and a framed view of the candlelit courtyard fountain.',
        curatorQuote: {
          text: 'Banctel achieves that rarest paradox: astonishing technical complexity that tastes effortless and emotionally grounding.',
          curator: 'Luc Moreau',
          role: 'Michelin Guide Reviewer & Columnist',
        },
      },
      {
        id: 'paris-officine-buly',
        cityId: 'paris',
        name: 'Officine Universelle Buly 1803',
        nativeName: 'Officine Universelle Buly',
        category: 'Boutiques',
        tagline: '19th-century apothecary wonder with bespoke calligraphy and botanical formulations.',
        description:
          'Founded in 1803 by the fabled Jean-Vincent Bully, this restored boutique on Rue Bonaparte feels like stepping into a Balzac novel. Polished walnut apothecary drawers, hand-painted ceramic tiles, and Italian marble counters showcase water-based perfumes (Eau Triple), natural plant oils, and plant-based dental balms. Every purchase is hand-inscribed by an in-house calligrapher using antique nibs and sumi ink.',
        editorialVerdict:
          'The antithesis of generic duty-free cosmetics. A tactile, sensory temple of craftsmanship and historical reverence.',
        atmosphere: ['Old-World Apothecary', 'Scented Sanctuary', 'Bespoke Calligraphy', 'Artisanal Care'],
        rating: 9.6,
        curatorScore: '9.6 / 10 Curated',
        priceLevel: '€€€',
        neighborhood: 'Saint-Germain-des-Prés, 6th Arr.',
        address: '6 Rue Bonaparte, 75006 Paris, France',
        phone: '+33 1 43 29 02 50',
        website: 'https://www.buly1803.com',
        hours: [
          { days: 'Tuesday – Saturday', time: '11:00 – 19:00' },
          { days: 'Monday', time: '12:00 – 19:00' },
          { days: 'Sunday', time: 'Closed' },
        ],
        bestTimeToVisit: 'Midday weekday when the calligrapher has ample time to craft a personalized keepsake box.',
        dressCode: 'Smart Casual.',
        images: [
          '/images/place_paris_cafe.jpg',
          '/images/hero_paris.jpg',
        ],
        coordinates: { lat: 48.8569, lng: 2.3341 },
        insiderTip:
          'Ask for the Baume des Muses lip balm in an engraved acetate case with your recipient’s initials gilded on top.',
        curatorQuote: {
          text: 'An olfactory cathedral that honors the ritual of grooming with romantic French rigor.',
          curator: 'Camille Villon',
          role: 'Art of Living Editor',
        },
      },
    ],
  },
  {
    id: 'tokyo',
    name: 'Tokyo',
    country: 'Japan',
    region: 'Asia',
    tagline: 'Architectural minimalism, cedar-scented tea alcoves, and quiet precision.',
    editorialDescription:
      'Beyond the kinetic neon crosswalks lies a Tokyo of deep serenity: the quiet rustle of bamboo groves in Aoyama, the slow drip of aged Nel drip coffee in quiet alleyways, and cedar facades that celebrate the impermanence of time.',
    badge: 'Brutalist Form & Tea Culture',
    heroImage: '/images/city_tokyo.jpg',
    galleryImages: [
      '/images/city_tokyo.jpg',
      '/images/place_tokyo_garden.jpg',
      '/images/hero_paris.jpg',
    ],
    timezone: 'Asia/Tokyo',
    coordinates: { lat: 35.6762, lng: 139.6503 },
    weather: {
      tempC: 22,
      tempF: 72,
      condition: 'Crisp & Diffused Sun',
      humidity: '52%',
      wind: '6 km/h E',
      goldenHour: '17:18',
      uvIndex: '4 (Moderate)',
      highLow: '24° / 16°',
    },
    insiderTips: [
      {
        id: 'tip-t1',
        title: 'Morning Silence at Nezu Garden',
        category: 'Quiet Refuge',
        description: 'While crowds flock to Senso-ji, the private forested stroll garden at the Nezu Museum in Minami-Aoyama features 4 rustic teahouses and stone buddhas amidst total tranquility.',
        curatorName: 'Kenzo Takahashi',
        curatorRole: 'Architectural Critic & Tokyo Native',
      },
      {
        id: 'tip-t2',
        title: 'Kissaten Espresso Rituals',
        category: 'Coffee Culture',
        description: 'Traditional Japanese coffee masters practice Nel drip extraction with beans aged up to thirty years. Silence is deeply respected; speak only in quiet murmurs.',
        curatorName: 'Yuki Moriyama',
        curatorRole: 'Culinary Anthropologist',
      },
      {
        id: 'tip-t3',
        title: 'Subway Footwear Etiquette',
        category: 'Cultural Etiquette',
        description: 'Slip-on leather loafers or minimalist Japanese sneakers make the frequent transitions at ryokans, tearooms, and galleries effortless.',
        curatorName: 'Reiko Endo',
        curatorRole: 'Lifestyle & Design Director',
      },
    ],
    places: [
      {
        id: 'tokyo-nezu-museum',
        cityId: 'tokyo',
        name: 'Nezu Museum & Bamboo Forest',
        nativeName: '根津美術館',
        category: 'Museums',
        tagline: 'Kengo Kuma’s bamboo colonnade opening onto an ancient moss sanctuary.',
        description:
          'Designed by master architect Kengo Kuma, the Nezu Museum in Minami-Aoyama is a triumph of contemporary Japanese organic architecture. Visitors approach via an ethereal, 50-meter covered corridor bordered by towering bamboo stalks and dark cedar slats. Inside, pre-modern Japanese and East Asian treasures—screens, bronze celadon, and lacquerware—are exhibited in whisper-soft gallery rooms. The glass rear wall looks out onto a multi-tiered moss garden featuring stone lanterns and rustic teahouses.',
        editorialVerdict:
          'Tokyo’s most harmonious union of contemporary architectural restraint and traditional garden landscaping.',
        atmosphere: ['Kengo Kuma Design', 'Bamboo Canopy', 'Moss & Stone Teahouses', 'Profound Quiet'],
        rating: 9.9,
        curatorScore: '9.9 / 10 Curated',
        priceLevel: '€€',
        neighborhood: 'Minami-Aoyama, Minato-ku',
        address: '6-5-1 Minamiaoyama, Minato City, Tokyo 107-0062, Japan',
        phone: '+81 3-3400-2536',
        website: 'https://www.nezu-muse.or.jp',
        hours: [
          { days: 'Wednesday – Sunday', time: '10:00 – 17:00' },
          { days: 'Monday & Tuesday', time: 'Closed' },
        ],
        bestTimeToVisit: 'Thursday at 10:15 just as the garden cafe opens overlooking the koi pond.',
        dressCode: 'Minimalist Contemporary / Smart Casual.',
        images: [
          '/images/place_tokyo_garden.jpg',
          '/images/city_tokyo.jpg',
        ],
        coordinates: { lat: 35.6625, lng: 139.7188 },
        insiderTip:
          'After viewing the exhibits, walk along the lower stone path in the garden past the stone pagodas to discover the NEZUCAFÉ hidden among the trees.',
        curatorQuote: {
          text: 'The transition from the bustling designer boutiques of Omotesando to the bamboo gallery is a physical decompression of the soul.',
          curator: 'Sora Nishida',
          role: 'Tokyo Architecture Fellow',
        },
      },
      {
        id: 'tokyo-cafe-de-l-ambre',
        cityId: 'tokyo',
        name: 'Café de L\'Ambre',
        nativeName: 'カフェ・ド・ランブル',
        category: 'Cafes',
        tagline: 'Legendary Ginza kissaten aging vintage coffee beans for decades.',
        description:
          'Founded in 1948 by the late Sekiguchi Ichiro, Café de L’Ambre serves only coffee—no tea, no food, no compromises. The intimate interior retains its 1970s curved counter, leather bar stools, and amber lighting. Here, rare raw coffee beans are stored in burlap sacks in climate-controlled lockers and aged for ten, twenty, or even forty years before being roasted in small batches and extracted through handmade cloth filters (nel drip).',
        editorialVerdict:
          'A pilgrimage site for pure coffee worship. Order the "Blanc et Noir" or a 1995 Cuban vintage brew.',
        atmosphere: ['Nel Drip Mastery', 'Vintage Bean Aging', 'Mid-Century Ginza', 'Uncompromising Focus'],
        rating: 9.8,
        curatorScore: '9.8 / 10 Curated',
        priceLevel: '€€',
        neighborhood: 'Ginza, Chuo-ku',
        address: '8-10-15 Ginza, Chuo City, Tokyo 104-0061, Japan',
        phone: '+81 3-3571-1551',
        website: 'https://www.h6.dion.ne.jp/~lambre/',
        hours: [
          { days: 'Tuesday – Saturday', time: '12:00 – 21:00' },
          { days: 'Sunday & Holidays', time: '12:00 – 19:00' },
          { days: 'Monday', time: 'Closed' },
        ],
        bestTimeToVisit: 'Mid-afternoon between 15:00 and 16:30 for unhurried observation of the master baristas.',
        dressCode: 'Casual Respectful.',
        images: [
          '/images/city_tokyo.jpg',
          '/images/place_tokyo_garden.jpg',
        ],
        coordinates: { lat: 35.6678, lng: 139.7612 },
        insiderTip:
          'Take a seat at the circular counter to observe the master slowly rotate the cotton filter over amber glassware.',
        curatorQuote: {
          text: 'The coffee possesses the viscous body and nuanced depth of a rare vintage cognac.',
          curator: 'Tatsuya Ono',
          role: 'Gastronomy Columnist',
        },
      },
      {
        id: 'tokyo-meiji-jingu',
        cityId: 'tokyo',
        name: 'Meiji Jingu Sacred Forest',
        nativeName: '明治神宮',
        category: 'Landmarks',
        tagline: '170 acres of consecrated evergreen forest and towering cypress torii gates.',
        description:
          'Created in 1920 with over 100,000 trees donated from across Japan and hand-planted by volunteer citizens, Meiji Jingu was engineered to become a self-sustaining sacred forest in 100 years. Today, stepping beneath the colossal 1,500-year-old Taiwanese cypress Torii gate replaces the roar of Harajuku with the crunch of river gravel underfoot and the deep, clean perfume of evergreen resin.',
        editorialVerdict:
          'An engineering and spiritual miracle of urban forestry. Wash hands and rinse at the temizuya water pavilion before approaching.',
        atmosphere: ['Sacred Forest', 'Cypress Torii', 'Spiritual Stillness', 'Shinto Architecture'],
        rating: 9.7,
        curatorScore: '9.7 / 10 Curated',
        priceLevel: '€',
        neighborhood: 'Yoyogi / Shibuya-ku',
        address: '1-1 Yoyogikamizonacho, Shibuya City, Tokyo 151-8557, Japan',
        phone: '+81 3-3379-5511',
        website: 'https://www.meijijingu.or.jp',
        hours: [
          { days: 'Daily', time: 'Sunrise to Sunset (06:00 – 18:00)' },
        ],
        bestTimeToVisit: 'At sunrise (06:30) before tour groups arrive, when morning mist hangs over the towering canopy.',
        dressCode: 'Modest / Respectful.',
        images: [
          '/images/place_tokyo_garden.jpg',
          '/images/city_tokyo.jpg',
        ],
        coordinates: { lat: 35.6764, lng: 139.6993 },
        insiderTip:
          'Write a wish on an Ema (wooden votive plaque) and hang it around the sacred camphor trees framing the main courtyard.',
        curatorQuote: {
          text: 'The temperature noticeably drops by two degrees as you cross the threshold into the forest canopy.',
          curator: 'Emi Tanaka',
          role: 'Cultural Geographer',
        },
      },
    ],
  },
  {
    id: 'rome',
    name: 'Rome',
    country: 'Italy',
    region: 'Mediterranean',
    tagline: 'Sun-warmed travertine palazzos, secret courtyard fountains, and Baroque theater.',
    editorialDescription:
      'Rome is not an open-air museum to be rushed; it is an enduring conversation between golden afternoon light and 2,000 years of hand-carved stone. In the quiet vicoli behind the Campo de\' Fiori, ivy spills over ochre stucco and espresso cups clatter against weathered zinc.',
    badge: 'Travertine & Renaissance Grandeur',
    heroImage: '/images/city_rome.jpg',
    galleryImages: [
      '/images/city_rome.jpg',
      '/images/place_rome_pantheon.jpg',
      '/images/hero_paris.jpg',
    ],
    timezone: 'Europe/Rome',
    coordinates: { lat: 41.9028, lng: 12.4964 },
    weather: {
      tempC: 25,
      tempF: 77,
      condition: 'Sunlit Azure Skies',
      humidity: '42%',
      wind: '11 km/h SW',
      goldenHour: '19:28',
      uvIndex: '5 (Moderate)',
      highLow: '27° / 18°',
    },
    insiderTips: [
      {
        id: 'tip-r1',
        title: 'The Midday Pantheon Oculous',
        category: 'Sacred Architecture',
        description: 'On cloudless afternoons between 12:00 and 13:30, a solid cylinder of golden light cuts through the 9-meter unglazed central opening, illuminating the marble floor roundels with astronomical precision.',
        curatorName: 'Gianluca Moretti',
        curatorRole: 'Classical Antiquities Scholar',
      },
      {
        id: 'tip-r2',
        title: 'Roman Coffee Counter Protocol',
        category: 'Espresso Rituals',
        description: 'Pay at the cassa first, obtain your receipt (scontrino), and place a small coin on the marble bar before ordering. Never order cappuccino after 11:00 am.',
        curatorName: 'Flavia Rossi',
        curatorRole: 'Roman Epicurean Author',
      },
      {
        id: 'tip-r3',
        title: 'Rooftop Aperitivo Timing',
        category: 'Sunset Vantage',
        description: 'Ascend the Aventine or Janiculum hill 45 minutes before twilight. As church bells toll across the seven hills, the terracotta tile sea ignites in crimson.',
        curatorName: 'Matteo Bellini',
        curatorRole: 'Architect & Photographer',
      },
    ],
    places: [
      {
        id: 'rome-pantheon',
        cityId: 'rome',
        name: 'The Pantheon & Rotonda',
        nativeName: 'Pantheon di Roma',
        category: 'Landmarks',
        tagline: 'The unreinforced concrete dome of Emperor Hadrian standing unbroken for two millennia.',
        description:
          'Completed around 125 AD under Emperor Hadrian, the Pantheon remains the world’s largest unreinforced concrete dome—a spherical marvel of Roman engineering where interior diameter (43.3m) precisely equals interior height. Sixteen monolith granite columns imported from Egypt guard the portico. Inside, the unglazed oculus opens directly to the celestial heavens, allowing rain, starlight, and sunbeams to pour onto porphyry and pavonazzetto marble floors.',
        editorialVerdict:
          'A spiritual and mathematical masterpiece of antiquity. Early morning visits before noon reveal the cleanest light rays.',
        atmosphere: ['Ancient Engineering', 'Oculus Sunbeams', 'Granite Colonnades', 'Imperial Majesty'],
        rating: 9.9,
        curatorScore: '9.9 / 10 Curated',
        priceLevel: '€',
        neighborhood: 'Pigna / Piazza della Rotonda',
        address: 'Piazza della Rotonda, 00186 Roma RM, Italy',
        phone: '+39 06 6830 0230',
        website: 'https://direzionemuseiroma.cultura.gov.it',
        hours: [
          { days: 'Monday – Sunday', time: '09:00 – 19:00' },
          { days: 'Last Entry', time: '18:15' },
        ],
        bestTimeToVisit: 'At 12:30 on a clear day to witness the sunlight spotlight Raphael’s tomb.',
        dressCode: 'Modest Attire (Shoulders and knees must be covered).',
        images: [
          '/images/place_rome_pantheon.jpg',
          '/images/city_rome.jpg',
        ],
        coordinates: { lat: 41.8986, lng: 12.4769 },
        insiderTip:
          'Notice the subtle drain holes in the convex marble floor directly beneath the oculus, designed 2,000 years ago to evacuate rainwater instantly.',
        curatorQuote: {
          text: 'Stepping into this sphere is one of the few experiences on earth that instantly renders all modern cynicism obsolete.',
          curator: 'Prof. Dario Valenti',
          role: 'Roman Archaeology Chair',
        },
      },
      {
        id: 'rome-sant-eustachio',
        cityId: 'rome',
        name: 'Sant\'Eustachio Il Caffè',
        nativeName: 'Sant’Eustachio Il Caffè',
        category: 'Cafes',
        tagline: 'Wood-roasted beans and velvety gran caffè prepared behind secret silver shields.',
        description:
          'Established in 1938 opposite the Palazzo Madama, Sant’Eustachio is legendary for its velvety, naturally sweet espresso with an impossibly thick crema. The water is sourced from the ancient Aqua Virgo aqueduct, and beans are roasted over slow wood fires. Baristas guard their extraction technique behind stainless steel screens, delivering cups of gran caffè that have enchanted presidents, film directors, and locals for generations.',
        editorialVerdict:
          'Rome’s quintessential coffee pilgrimage. If you prefer unadulterated bitterness, specify "senza zucchero" before they brew.',
        atmosphere: ['1930s Historic Bar', 'Secret Crema Technique', 'Aqua Virgo Water', 'Lively Banter'],
        rating: 9.7,
        curatorScore: '9.7 / 10 Curated',
        priceLevel: '€€',
        neighborhood: 'Sant\'Eustachio / Navona',
        address: 'Piazza di S. Eustachio, 82, 00186 Roma RM, Italy',
        phone: '+39 06 6880 2048',
        website: 'https://santeustachioilcaffe.it',
        hours: [
          { days: 'Sunday – Thursday', time: '07:30 – 01:00' },
          { days: 'Friday & Saturday', time: '07:30 – 01:30' },
        ],
        bestTimeToVisit: '08:15 am with a fresh cornetto al pistacchio standing at the brass bar.',
        dressCode: 'Casual Italian.',
        images: [
          '/images/city_rome.jpg',
          '/images/place_rome_pantheon.jpg',
        ],
        coordinates: { lat: 41.8981, lng: 12.4754 },
        insiderTip:
          'Pick up a tin of their chocolate-covered coffee beans (chicchi ricoperti di cioccolato) to slip into your coat pocket.',
        curatorQuote: {
          text: 'The crema here does not merely float—it cushions the palate like warm velvet.',
          curator: 'Costanza Leone',
          role: 'Culinary Historian',
        },
      },
      {
        id: 'rome-villa-borghese',
        cityId: 'rome',
        name: 'Galleria Borghese',
        nativeName: 'Galleria Borghese',
        category: 'Museums',
        tagline: 'Bernini’s astonishing marble sculptures and Caravaggio masterworks in a cardinal palazzo.',
        description:
          'Commissioned by Cardinal Scipione Borghese in the early 17th century to house his voracious art collection, this villa houses what is arguably the highest concentration of artistic genius per square meter in Italy. Bernini’s Apollo and Daphne captures marble transforming into flesh and laurel leaves with supernatural fluidity, surrounded by intense canvases by Caravaggio, Raphael, and Titian.',
        editorialVerdict:
          'Strictly limited two-hour timed entries ensure spacious, unhurried contemplation. Book well in advance.',
        atmosphere: ['Baroque Grandeur', 'Bernini Masterpieces', 'Frescoed Vaults', 'Sculptural Drama'],
        rating: 9.9,
        curatorScore: '9.9 / 10 Curated',
        priceLevel: '€€€',
        neighborhood: 'Pinciano / Villa Borghese',
        address: 'Piazzale Scipione Borghese, 5, 00197 Roma RM, Italy',
        phone: '+39 06 841 3979',
        website: 'https://galleriaborghese.beniculturali.it',
        hours: [
          { days: 'Tuesday – Sunday', time: '09:00 – 19:00 (2-hour slots)' },
          { days: 'Monday', time: 'Closed' },
        ],
        bestTimeToVisit: 'The 17:00 – 19:00 sunset entry slot when amber light filters through high palazzo windows.',
        dressCode: 'Smart Casual.',
        images: [
          '/images/city_rome.jpg',
          '/images/place_rome_pantheon.jpg',
        ],
        coordinates: { lat: 41.9142, lng: 12.4922 },
        insiderTip:
          'Begin on the upper floor with Caravaggio and Raphael before descending to the ground floor sculptures as the crowds reverse.',
        curatorQuote: {
          text: 'Bernini did not carve stone; he seduced marble into becoming warm, yielding skin.',
          curator: 'Leonardo Ferri',
          role: 'Curator of European Sculpture',
        },
      },
    ],
  },
  {
    id: 'kyoto',
    name: 'Kyoto',
    country: 'Japan',
    region: 'Asia',
    tagline: 'Ancient cedar shoji, dry landscape raked gravel, and seasonal kaiseki precision.',
    editorialDescription:
      'Kyoto lives in the whisper of wooden geta sandals upon stone bridges, the scent of burning hinoki incense at dusk, and moss gardens tended with small bamboo tweezers across five generations.',
    badge: 'Zen Gardens & Sukiya Architecture',
    heroImage: '/images/place_tokyo_garden.jpg',
    galleryImages: [
      '/images/place_tokyo_garden.jpg',
      '/images/city_tokyo.jpg',
    ],
    timezone: 'Asia/Tokyo',
    coordinates: { lat: 35.0116, lng: 135.7681 },
    weather: {
      tempC: 19,
      tempF: 66,
      condition: 'Tranquil Mist & Cool Pines',
      humidity: '56%',
      wind: '4 km/h N',
      goldenHour: '17:22',
      uvIndex: '3 (Moderate)',
      highLow: '21° / 13°',
    },
    insiderTips: [
      {
        id: 'tip-k1',
        title: 'Ryoan-ji at Dawn Opening',
        category: 'Zen Contemplation',
        description: 'Arrive at Ryoan-ji at 07:50 am. When the wooden gates open at 08:00, you will have ten minutes alone with the fifteen stones in raked white granite before any tours arrive.',
        curatorName: 'Master Keisuke Sato',
        curatorRole: 'Zen Landscape Custodian',
      },
      {
        id: 'tip-k2',
        title: 'Kaiseki Footwear Preparation',
        category: 'Dining Etiquette',
        description: 'Always wear pristine, clean white socks for traditional tatami dining rooms. Refrain from heavy perfumes out of respect for delicate dashi broths.',
        curatorName: 'Sayaka Murata',
        curatorRole: 'Kyoto Hospitality Guide',
      },
    ],
    places: [
      {
        id: 'kyoto-ryoanji',
        cityId: 'kyoto',
        name: 'Ryōan-ji Zen Temple & Rock Garden',
        nativeName: '龍安寺',
        category: 'Landmarks',
        tagline: 'Fifteen mysterious stones arranged on a sea of raked white granite gravel.',
        description:
          'Dating to the late 15th century, the karesansui (dry landscape) rock garden of Ryōan-ji is the quintessential expression of Zen minimalism. Fifteen rocks of varying contours are arranged within an austere rectangle of raked quartz pebbles, bordered by an oiled clay wall bearing the patina of five centuries. The layout is calculated such that from any vantage point on the wooden veranda, at least one rock is hidden from view.',
        editorialVerdict:
          'A timeless monument to the beauty of incompletion and mindful contemplation. Sit in silence on the cedar deck.',
        atmosphere: ['Dry Zen Rock Garden', 'Wabi-Sabi Patina Wall', 'Cedar Veranda', 'Profound Contemplation'],
        rating: 9.8,
        curatorScore: '9.8 / 10 Curated',
        priceLevel: '€',
        neighborhood: 'Ukyo-ku',
        address: '13 Ryoanji Goryonoshitacho, Ukyo Ward, Kyoto 616-8001, Japan',
        phone: '+81 75-463-2216',
        website: 'http://www.ryoanji.jp',
        hours: [
          { days: 'Daily', time: '08:00 – 17:00 (March – November)' },
        ],
        bestTimeToVisit: '08:00 sharp when the wooden temple gates slide open.',
        dressCode: 'Modest & Quiet (Clean socks mandatory for wooden verandas).',
        images: [
          '/images/place_tokyo_garden.jpg',
          '/images/city_tokyo.jpg',
        ],
        coordinates: { lat: 35.0345, lng: 135.7182 },
        insiderTip:
          'Look for the stone tsukubai water basin engraved with four kanji surrounding the central square: "Ware tada taru o shiru" ("I learn only to be contented").',
        curatorQuote: {
          text: 'It teaches you that what is absent is just as deliberate as what is present.',
          curator: 'Kazuo Ishiguro',
          role: 'Architecture Essayist',
        },
      },
    ],
  },
  {
    id: 'copenhagen',
    name: 'Copenhagen',
    country: 'Denmark',
    region: 'Europe',
    tagline: 'Sculptural Danish furniture, natural harbor baths, and progressive Nordic gastronomy.',
    editorialDescription:
      'Copenhagen proves that human warmth and rigorous architectural minimalism are not opposites. Along the quiet canals of Christianshavn, timber houses shelter candlelit studios where designers sculpt oiled oak and hand-thrown ceramics.',
    badge: 'Nordic Warmth & Organic Modernism',
    heroImage: '/images/hero_paris.jpg',
    galleryImages: [
      '/images/hero_paris.jpg',
      '/images/place_paris_cafe.jpg',
    ],
    timezone: 'Europe/Copenhagen',
    coordinates: { lat: 55.6761, lng: 12.5683 },
    weather: {
      tempC: 17,
      tempF: 63,
      condition: 'Clean Baltic Light & Breeze',
      humidity: '55%',
      wind: '14 km/h W',
      goldenHour: '19:15',
      uvIndex: '2 (Low)',
      highLow: '19° / 11°',
    },
    insiderTips: [
      {
        id: 'tip-c1',
        title: 'Bicycle Flow on the Inderhavnsbroen',
        category: 'Urban Mobility',
        description: 'Rent an understated single-speed city bike. Use crisp hand signals when stopping and observe the silent green wave of cycling traffic during golden hour.',
        curatorName: 'Mads Lindholm',
        curatorRole: 'Urban Design Fellow',
      },
    ],
    places: [
      {
        id: 'copenhagen-design-museum',
        cityId: 'copenhagen',
        name: 'Designmuseum Danmark',
        nativeName: 'Designmuseum Danmark',
        category: 'Museums',
        tagline: 'The temple of Danish modernism, Arne Jacobsen, and Finn Juhl chairs.',
        description:
          'Housed inside King Frederik’s 18th-century Rococo hospital with its tranquil central grassy courtyard, Designmuseum Danmark chronicles the golden age of Scandinavian functionalism. Original prototypes by Hans Wegner, Kaare Klint, and Poul Henningsen demonstrate how ergonomic utility can reach sculptural transcendence.',
        editorialVerdict:
          'Essential visiting for anyone captivated by proportion, tactile materials, and timeless craft.',
        atmosphere: ['Scandinavian Minimalism', 'Iconic Chairs', 'Hospital Courtyard', 'Tactile Woodwork'],
        rating: 9.7,
        curatorScore: '9.7 / 10 Curated',
        priceLevel: '€€',
        neighborhood: 'Bredgade / Frederiksstaden',
        address: 'Bredgade 68, 1260 København, Denmark',
        phone: '+45 33 18 56 56',
        website: 'https://designmuseum.dk',
        hours: [
          { days: 'Tuesday – Sunday', time: '10:00 – 18:00' },
          { days: 'Thursday', time: '10:00 – 20:00' },
          { days: 'Monday', time: 'Closed' },
        ],
        bestTimeToVisit: 'Thursday evening during late openings, followed by coffee in the courtyard.',
        dressCode: 'Nordic Clean / Casual.',
        images: [
          '/images/hero_paris.jpg',
          '/images/place_paris_cafe.jpg',
        ],
        coordinates: { lat: 55.6865, lng: 12.5925 },
        insiderTip:
          'The museum shop is one of Europe’s finest repositories for archival design books and limited-edition ceramics.',
        curatorQuote: {
          text: 'Here, a chair is not furniture; it is an intimate posture toward daily life.',
          curator: 'Astrid Møller',
          role: 'Danish Design Historian',
        },
      },
    ],
  },
];
